packages:
  common: !include common.yaml

esphome:
  name: c3-0
  friendly_name: c3-0
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  #flash_size: 4MB
  variant: esp32c3
  framework:
    type: esp-idf

remote_receiver:
  pin:
    number: GPIO5
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all
  rmt_channel: 3
