# Home Assistant Core Temperature Telemetry Package for C6
sensor:
  - platform: homeassistant
    id: inside_temperature
    entity_id: ${inside_temp_entity}
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: indoor_temp_label
            text: !lambda |-
              return weather::format_temp_with_trend(x, id(last_indoor_temp));

  - platform: homeassistant
    id: outside_temperature
    entity_id: ${weather_entity}
    attribute: temperature
    internal: true
    on_value:
      then:
        - lvgl.label.update:
            id: outdoor_temp_label
            text: !lambda |-
              return weather::format_temp_with_trend(x, id(last_outdoor_temp));
